changelog:
  categories:
    - title: Changed
      labels:
        - removed
    - title: Added
      labels:
        - features
    - title: Changed
      labels:
        - improvements
    - title: Fixed
      labels:
        - fix
    - title: Other Changes
      labels:
        - "*"
